### ISSUE TITLE
Updater script does not exist

### ISSUE THREAD

**Issue by Pendrag00n** [Sterbweise/T6Server#1]
How am I suposed to run `mv ~/T6Server/plutonium-updater ~/T6Server/Plutonium/` when there is no `plutonium-updater` inside the folder?¿

![Tree](https://user-images.githubusercontent.com/88731722/187962370-c7069d02-1733-4867-9712-906c80f3abbd.png)

![lol](https://user-images.githubusercontent.com/88731722/187962908-6290a943-b30f-41c2-b143-4d3699e113da.png)

**Comment by Pendrag00n** [comment]
(Maybe I'm wrong) Recreate this by deleting T6Server/ a reinstalling everything from the beginning, somehow the installer wont install the updater into T6Server/

I fixed it by going to https://github.com/mxve/plutonium-updater.rs and doing it myself

**Comment by Sterbweise** [comment]
Yea, that right. Plutonium-updater is supposed to be downloaded with the install.sh script.
But the script is executed with the sudoers permission, so the user download path change to sudoers.
I will fix this. thank you for you return ;)
