### ISSUE TITLE
logs don't get created

### ISSUE THREAD

**Issue by xMonologue** [Sterbweise/T6Server#4]
for some reasons my logs files for my two servers don't get created, anyones know how to fix this issue? Basically I can't link IW4M to my two servers

**Comment by xMonologue** [comment]
not sure if it has to do with the mod change I made

**Comment by Sterbweise** [comment]
I'll take a look at the issue. But Firstly, you need to verify the logs configuration and access settings in your dedicated.cfg:

```
g_logSync 2                                     // 0 only flush on game end, 1 flush when buffer full, 2 always flush after a write, 3 append to old logs. (Keep this at 2 if you plan on using a 3rd party admin tool)
g_log "logs\games_zm.log"                       // If you choose to use this make sure the filename is unique for each server!
```

For IW4M connection, you need to properly configure this section:

```
rcon_password ""                                // RemoteCONtrol password. !!Do NOT skip if you plan on using a 3rd party admin tool such as B3 or IW4m-Admin!!
rcon_rate_limit "500"                           // Rate limit RCon; limit is per IP; range is 0 to 10 000; value is in milliseconds. Lower this if you use IW4mA's Game Interface.
rconWhitelistAdd "127.0.0.1"                    // Command used to add an IP address to the whitelist. When no IP is added all IPs can send rcon commands.
rconWhitelistAdd "192.168.0.7"                  // If it is set only the whitelisted IPs and loopback (127.0.0.0/8) can send commands.
rconWhitelistAdd "10.0.0.12"                    // The command can be called multiple times to add more than one IP to the whitelist.
rconWhitelistAdd "172.16.8.7"                   // If IW4M or other third party tools are not on the same machine edit this IP address to the IP address of the machine you will use to host IW4M on.
```

Note:
- Make sure to set a unique and secure rcon_password (remove the duplicate line)
- The IPs in the whitelist should match your network configuration
- Adjust the rcon_rate_limit according to your needs if using IW4mA
- Ensure the log filename is unique for each server instance

**Comment by Sterbweise** [comment]
Hi, the latest release is here. It fixes the r4520 update, many problems, and improves stability and architecture.

#### ⚠️ Attention - Significant Modifications

I advise you to read [the release notes](https://github.com/Sterbweise/T6Server/releases) to be more aware.

The most important change is the new installation process and the architecture to run your server well.

For the installation, take a look here: [#installation](https://github.com/Sterbweise/T6Server/blob/main/README.md#installation)

---

**Full documentation available: [#documentation](https://github.com/Sterbweise/T6Server/blob/main/README.md)**
